---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: bento/centos-6.7
  - name: bento/centos-7.2

suites:
  - name: default
    run_list:
      - recipe[project::default]
    attributes:
